networks:
  default:
    name: urbs-network
    driver: bridge

services:
  mysql:
    container_name: urbs-mysql
    image: mysql:8.0
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: busanalysis_dw
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql/
      - ./data/mysql-files:/var/lib/mysql-files/
    networks:
      - default

  jupyterlab:
    container_name: urbs-jupyterlab
    restart: unless-stopped
    user: root
    build: .
    image: urbs/gtfs-generator:0.1
    working_dir: /app/
    ports:
      - 8085:8085
      - 4040:4040
    volumes:
      - .:/app/
      - ./data/:/data/
    networks:
      - default
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: busanalysis_dw      